### ISSUE TITLE
Enable PySocks support when compiling for users with system proxy configuration

### ISSUE THREAD

**Issue by PatrykMis** [leibylucw/hearthstone-access-patcher#16]
Presently, when a user configures a system proxy in the system's Settings or Internet Options as SOCKS4 or SOCKS5, the patcher fails to download the zip file properly due to the absence of socks support.

By default, `Requests` utilizes the PySocks library if it's installed in the local Python environment or included in the compiled exe. Consequently, if `PySocks` (`socks.py`) is available, the download succeeds even when a system proxy is configured.

As stated in the [`Request`'s manual](https://requests.readthedocs.io/en/latest/user/advanced/#proxies), `Requests` can be installed with Socks proxy support:

```bash
$ pip install -U requests[socks]
```

This is equivalent for `pip install -U pysocks request`.

To ensure PySocks is enabled while compiling the application, include the library in the environment or explicitly enable it during compilation.

**Comment by leibylucw** [comment]
Closing, see #25
